owner: MinecraftAuthentication
repo: status

sites:
  - name: Site
    url: https://minecraftauth.me/
  - name: Minecraft
    check: "tcp-ping"
    url: $MINECRAFT_SERVER
    port: 25565
  - name: Mojang Login
    url: https://authserver.mojang.com/
  - name: Discord API
    url: https://discord.com/api/users/@me
    expectedStatusCodes:
      - 401
  - name: Patreon API
    url: https://www.patreon.com/api/oauth2/v2/campaigns/0/members
    expectedStatusCodes:
      - 401
  - name: Twitch Subscriptions API
    url: https://api.twitch.tv/helix/subscriptions
    expectedStatusCodes:
      - 401
  - name: YouTube Channels API
    url: https://www.googleapis.com/youtube/v3/channels
    expectedStatusCodes:
      - 403
  - name: Glimpse Sponsorship API
    url: https://api.glimpse.me/auth/access/me
    expectedStatusCodes:
      - 401
https://api.glimpse.me/auth/authorize
status-website:
  cname: status.minecraftauth.me
  logoUrl: https://minecraftauth.me/favicon.png
  theme: night
  name: Minecraft Authentication Status
  navbar:
    - title: Home
      href: https://minecraftauth.me
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
